#!/usr/bin/env bash
_symfony2_console_complete()
{
    local cmd_list=`$1 list --raw | sed 1d | awk '{ print $1 }'`
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "$cmd_list" -- $cur) )
}

_symfony2_app_console()
{
    _symfony2_console_complete 'app/console'
}

_symfony2_bin_symfony()
{
    _symfony2_console_complete 'bin/symfony'
}

complete -F _symfony2_app_console app/console
complete -F _symfony2_bin_symfony bin/symfony
